### ISSUE TITLE
Disable endVisible callback

### ISSUE THREAD

**Issue by rsaenen** [ng2-ui/infinite-list#2]
Hi,

Could you add an input to the ngui-infinite-list to disable (endVisible) emit ?

Thanks

**Comment by allenhwkim** [comment]
Could you provide more details?

**Comment by rsaenen** [comment]
```
@Directive({ selector: '[ngui-infinite-list]' })` 
export class NguiInfiniteListDirective {  
  @Input() horizontal: boolean;  
  @Input() enableWindowScroll : boolean = false;  
  @Input() disabledEndVisible: boolean = false;  
  @Output() endVisible = new EventEmitter();  
```

````
scrollListener = () => {  
    if (this.disabledEndVisible) {  
      let visible;
      if(this.enableWindowScroll){
        visible = this.elementVisible(this.endEl,window)
      } else {
        visible = this.elementVisible(this.endEl, this.el);
      }
      if (this.horizontal && (visible.left || visible.right)) {
        this.endVisible.emit(true); 
      } else if (!this.horizontal && (visible.top || visible.bottom)) {
        this.endVisible.emit(true); 
      }
    }
  }
 ```

**Comment by allenhwkim** [comment]
@rsaenen thanks for this detail. If you can make PR, please do so. You don't have to wait for me to copy/paste your code.

**Comment by rsaenen** [comment]
I'm getting a 403 when I make PR...

**Comment by allenhwkim** [comment]
Did you `git push` to this repository directly?

https://help.github.com/articles/creating-a-pull-request/

**Comment by rsaenen** [comment]
@allenhwkim I didn't push to master, I create a new branch and push it to make PR.
Do you want I fork this repo to make PR ?

**Comment by allenhwkim** [comment]
@rsaenen yes, you need to fork it.

**Comment by rsaenen** [comment]
PR is done.
Are you interested by a Input File component ? I begin to outsource mine :
https://github.com/rsaenen/ngx-input-file
